In [1]:
# Q1: Create a NumPy 1D-array and perform basic operations

import numpy as np

a = np.array([10, 20, 30, 40, 50])

print("Original:", a)
print("Addition:", a + 2)
print("Multiplication:", a * 3)
print("Division:", a / 2)

Original: [10 20 30 40 50]
Addition: [12 22 32 42 52]
Multiplication: [ 30  60  90 120 150]
Division: [ 5. 10. 15. 20. 25.]


In [2]:
# Q2(a): Reverse the NumPy array
# Q2(b): Find the most frequent value and its indices

arr = np.array([1, 2, 3, 6, 4, 5])
print("Reversed:", arr[::-1])

for x in [np.array([1,2,3,4,5,1,2,1,1,1]),
          np.array([1,1,1,2,3,4,2,4,3,3])]:
    u, c = np.unique(x, return_counts=True)
    m = u[np.argmax(c)]
    print("Array:", x)
    print("Most frequent:", m)
    print("Indices:", np.where(x == m)[0])

Reversed: [5 4 6 3 2 1]
Array: [1 2 3 4 5 1 2 1 1 1]
Most frequent: 1
Indices: [0 5 7 8 9]
Array: [1 1 1 2 3 4 2 4 3 3]
Most frequent: 1
Indices: [0 1 2]


In [3]:
# Q3(a): Access 1st row, 2nd column
# Q3(b): Access 3rd row, 1st column

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print("1st row, 2nd column:", arr[0, 1])
print("3rd row, 1st column:", arr[2, 0])

1st row, 2nd column: 20
3rd row, 1st column: 70


In [4]:
# Q4: Create a 1-D array using linspace and display its properties

a = np.linspace(10, 100, 25)

print("Array:", a)
print("Dimensions:", a.ndim)
print("Shape:", a.shape)
print("Total elements:", a.size)
print("Data type:", a.dtype)
print("Total bytes:", a.nbytes)

t = a.reshape(1, 25)
print("Transpose using reshape():\n", t.T)
print("Transpose using T:\n", a.T)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using T:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [5]:
# Q5: Create 2-D array, calculate statistics, reshape and resize

a = np.array([[10, 20, 30, 40],
              [50, 60, 70, 80],
              [90, 15, 20, 35]])

print("Mean:", np.mean(a))
print("Median:", np.median(a))
print("Maximum:", np.max(a))
print("Minimum:", np.min(a))
print("Unique:", np.unique(a))

reshaped_ucs420_1024160123 = a.reshape(4, 3)
resized_ucs420_1024160123 = np.resize(a, (2, 3))

print("Reshaped:\n", reshaped_ucs420_1024160123)
print("Resized:\n", resized_ucs420_1024160123)

Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized:
 [[10 20 30]
 [40 50 60]]
